name = "logicalmechanism/cogno_v2"
version = "0.1.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "GPL-3.0-or-later"
description = "A fully on-chain social media platform."

[repository]
user = "logicalmechanism"
project = "cogno_v2"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "v0.4.10"
source = "github"
